version: '3.9'
services:
  # https://hub.docker.com/_/httpd
  # The Apache HTTP Server Project
  apache-service:
    container_name: apache
    image: httpd:latest
    ports:
      - "80:80"

  # https://hub.docker.com/_/php
  php:
    container_name: php
    image: php:latest

  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD:
       MYSQL_DATABASE:
       MYSQL_USER:
       MYSQL_PASSWORD:

  # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - '8080:80'

  # https://hub.docker.com/_/wordpress
  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
    volumes:
      # access wp-content/themes/demo-theme/
      - ./wordpress/themes:/var/www/wp-content/themes:delegated
      # acess wp-content/plugins/demo-plugin/
      - ./wordpress/plugins:/var/www/wp-content/plugins:delegated